name = "image-storage-worker"
main = "worker.js"
compatibility_date = "2025-05-03"

[[d1_databases]]
binding = "DB"
database_name = "image_storage"
database_id = "${DB_ID}"

[assets]
directory = "./static"
binding = "ASSETS"